### ISSUE TITLE
Python related error

### ISSUE THREAD

**Issue by Carnaux** [Carnaux/NFT-Marker-Creator#4]
stderr: cache:INFO: generating port: libz.a... (this will be cached in "C:\Users\Daniel\.emscripten_cache\asmjs\libz.a" for subsequent builds)
Traceback (most recent call last):
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\emcc.py", line 3262, in <module>
    sys.exit(run(sys.argv))
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\emcc.py", line 1641, in run
    compile_source_file(i, input_file)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\emcc.py", line 1626, in compile_source_file
    args = get_clang_args([input_file]) + ['-c', '-o', output_file]
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\emcc.py", line 1607, in get_clang_args
    args = system_libs.process_args(args, shared.Settings)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\system_libs.py", line 1029, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\ports\zlib.py", line 55, in process_args
    get(ports, settings, shared)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\ports\zlib.py", line 46, in get
    return [shared.Cache.get('libz.a', create, what='port')]
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\cache.py", line 127, in get
    temp = creator()
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\ports\zlib.py", line 42, in create
    ports.run_commands([[shared.EMAR, 'rc', final] + o_s])
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\system_libs.py", line 817, in run_commands
    run_commands(commands)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\system_libs.py", line 35, in run_commands
    call_process(command)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\system_libs.py", line 28, in call_process
    shared.run_process(cmd, stdout=stdout, stderr=stderr)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\emscripten\1.38.29\tools\shared.py", line 170, in run_process
    proc = Popen(cmd, *args, **kw)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Users\Daniel\Desktop\webAssembly\emsdk\python\2.7.13.1_64bit\python-2.7.13.amd64\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 n�o � um aplicativo Win32 v�lido

exec error: 1

**Comment by Carnaux** [comment]
Maybe bit version error. Compiling app to 32bit using 64bit python

**Comment by kalwalt** [comment]
Which emscripten are you using? How did you install emscripten? Maybe you can try to update emscripten https://emscripten.org/docs/getting_started/downloads.html#updating-the-sdk
and maybe trying to clear the emmc cache with `emcc --clear-cache` as explained here: https://emscripten.org/docs/tools_reference/emcc.html

**Comment by Carnaux** [comment]
I update emscripten, but still another error. We need a third person, maybe is my setup. Tomorrow i will reinstall everything.

**Comment by Carnaux** [comment]
Yeaah!! It works!! I can build and receive data from the .iset file created in the MEMFS!!! @kalwalt can you test the new file?

**Comment by kalwalt** [comment]
Yeaahh! 🎉🚀💯💥🌈 I am Happy for you! How did you solve It? What was causing the issue? I Will test the new code this afternoon...😊

**Comment by kalwalt** [comment]
It works for me! We can rename the `tools/makemWin.js` to `tools/makem.js` and so deleting the old one, i will make a little PR for this.

**Comment by kalwalt** [comment]
i made this PR https://github.com/Carnaux/NFT-Marker-Creator/pull/5

**Comment by Carnaux** [comment]
> Yeaahh! 🎉🚀💯💥🌈 I am Happy for you! How did you solve It? What was causing the issue? I Will test the new code this afternoon...😊

I updated my emscripten and changed some cmd lines. In windows these flags are unused. And i also removed all wildcard `*`.
```
FLAGS += ' -msse';
FLAGS += ' -msse2';
FLAGS += ' -msse3';
FLAGS += ' -mssse3';
```
