### ISSUE TITLE
Added NFT demo

### ISSUE THREAD

**Issue by Carnaux** [Carnaux/NFT-Marker-Creator#42]
@kalwalt @nicolocarpignoli @ThorstenBux I just added a demo that you can use as soon as you finish to generate a marker, can you test it? And of course, any suggestions are welcome!

**Comment by kalwalt** [comment]
It's a nice and useful feature, i will test it! Thank you :smile:

**Comment by kalwalt** [comment]
Hi @Carnaux just tested the node app. It create the markers (i tested the pinball image) but at the end of the process I get this error: 

```
[info] Generator finished at 2020-04-15 11:59:43 +0200
--

Finished marker creation!
Now configuring demo! 

Error: ENOENT: no such file or directory, scandir '/home/walter/kalwalt-github/NFT-Marker-Creator/demo/public/marker/'
Error: ENOENT: no such file or directory, scandir '/home/walter/kalwalt-github/NFT-Marker-Creator/demo/public/marker/'
/home/walter/kalwalt-github/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1
var Module=typeof Module!=="undefined"?Module:{};var scope;if(typeof window!=="undefined"){scope=window}else if(typeof window=="undefined"){scope=global}else{scope=global}if(scope.artoolkit_wasm_url){var downloadWasm=function(url){return new Promise(function(resolve,reject){var wasmXHR=new XMLHttpRequest;wasmXHR.open("GET",url,true);wasmXHR.responseType="arraybuffer";wasmXHR.onload=function(){resolve(wasmXHR.response)};wasmXHR.onerror=function(){reject("error "+wasmXHR.status)};wasmXHR.send(null)})};var wasm=downloadWasm(scope.artoolkit_wasm_url);Module.instantiateWasm=function(imports,successCallback){console.log("instantiateWasm: instantiating synchronously");wasm.then(function(wasmBinary){console.log("wasm download finished, begin instantiating");var wasmInstantiate=WebAssembly.instantiate(new Uint8Array(wasmBinary),imports).then(function(output){console.log("wasm instantiation succeeded");successCallback(output.instance)}).ca

RuntimeError: abort(Error: ENOENT: no such file or directory, scandir '/home/walter/kalwalt-github/NFT-Marker-Creator/demo/public/marker/') at Error
    at jsStackTrace (/home/walter/kalwalt-github/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:24352)
    at stackTrace (/home/walter/kalwalt-github/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:24523)
    at process.abort (/home/walter/kalwalt-github/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:21199)
    at process.emit (events.js:321:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
    at process.abort (/home/walter/kalwalt-github/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:21230)
    at process.emit (events.js:321:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)

```
it seems that is required the folder `demo/public/marker/` i will retry manually creating that folder.
It's nice to see the confidece level at the beginning :smile: ! :

```
node app.js -i pinball.jpg
The EXIF info of this image is empty or it does not exist. Do you want to inform its properties manually?[y/n]
y
Inform the width and height: e.g W=200 H=400
W=1637 H=2048
Inform the DPI: e.g DPI=220 [Default = 72](Press enter to use default)
DPI=220

Confidence level: [ * * * * * ] 5/5 || Entropy: 5.17 || Current max: 5.17 min: 4.6

Do you want to continue? (Y/N)
y
[info] --
Generator started at 2020-04-15 11:54:04 +0200

```

**Comment by kalwalt** [comment]
With the `marker` folder all went fine!

**Comment by Carnaux** [comment]
I will make some adjustments so it creates the folder
