### ISSUE TITLE
Error on processing jpg images: abort(TypeError: Cannot read property 'value' of undefined) at Error

### ISSUE THREAD

**Issue by bnn1** [Carnaux/NFT-Marker-Creator#66]
When running `node app -i imgname` I get a big fat error that ends with the following:

```javascript
RuntimeError: abort(TypeError: Cannot read property 'value' of undefined) at Error
    at jsStackTrace (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:23770)
    at stackTrace (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:23941)
    at process.abort (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:20844)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
    at process.abort (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:20875)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
```
node version: 15.5.1
manjaro v20.2.1
kernel 5.10.2.2-manjaro

I've tried two jpg images: one is a random internet image and the other is an image of myself. 
png files are processed without errors.

upd. I found that big error text is just the code of the NftMarkerCreator_wasm file...
The actual error is:
```javascript
TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:112
      throw ex;
      ^

RuntimeError: abort(TypeError: Cannot read property 'value' of undefined) at Error
    at jsStackTrace (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1033:13)
    at stackTrace (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1047:12)
    at process.abort (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:903:44)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
    at process.abort (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:905:9)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
```

**Comment by bnn1** [comment]
I found that big error text is just the code of the `NftMarkerCreator_wasm` file... 
The actual error is:
```
TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:112
      throw ex;
      ^

RuntimeError: abort(TypeError: Cannot read property 'value' of undefined) at Error
    at jsStackTrace (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1033:13)
    at stackTrace (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1047:12)
    at process.abort (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:903:44)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
    at process.abort (/home/boris/webdev/personal/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:905:9)
    at process.emit (node:events:376:20)
    at emit (node:internal/process/promises:202:22)
    at processPromiseRejections (node:internal/process/promises:223:25)
    at processTicksAndRejections (node:internal/process/task_queues:94:32)
```
Can't modify initial post because browser window freezes when I'm trying to do so.

**Comment by MaXiaoMa** [comment]
The error occurred in the following code (app.js line:319): 
```
 let dpi = Math.min(parseInt(metadata.XResolution.value), parseInt(metadata.YResolution.value));
                    if (dpi == null || dpi == undefined || dpi == NaN) {
                        console.log("\nWARNING: No DPI value found! Using 72 as default value!\n")
                        dpi = 72;
                    }
```
because the metadata object only has a few tags , no XResolution, no YResolution....
```
{ 'Bits Per Sample': { value: 8, description: '8' },
  'Image Height': { value: 500, description: '500px' },
  'Image Width': { value: 500, description: '500px' },
  'Color Components': { value: 3, description: '3' },
  Subsampling:
   { value: [ [Array], [Array], [Array] ],
     description: 'YCbCr4:2:0 (2 2)' } }
```

**Comment by DeveloperHashmi** [comment]
I'm also getting this error while making marker of jpg image.
![image](https://user-images.githubusercontent.com/51310612/105695071-a619bd00-5f27-11eb-815e-e3a89ac68f55.png)

**Comment by Carnaux** [comment]
the EXIF reader was updated, so please, check the new update to see if those errors still happening,
