### ISSUE TITLE
Error Failed to parse URL from

### ISSUE THREAD

**Issue by luke-momentusresearch** [Carnaux/NFT-Marker-Creator#93]
_RuntimeError: abort(TypeError: Failed to parse URL from /Users/user/Desktop/project/webar/markerCreatorAppFolder/libs/NftMarkerCreator_wasm.wasm) at Error
    at jsStackTrace (/Users/user/Desktop/project/webar/markerCreatorAppFolder/libs/NftMarkerCreator_wasm.js:1:24659)
    at stackTrace (/Users/user/Desktop/project/webar/markerCreatorAppFolder/libs/NftMarkerCreator_wasm.js:1:24830)
    at process.abort (/Users/user/Desktop/project/webar/markerCreatorAppFolder/libs/NftMarkerCreator_wasm.js:1:21515)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
    at process.abort (/Users/user/Desktop/project/webar/markerCreatorAppFolder/libs/NftMarkerCreator_wasm.js:1:21546)
    at process.emit (node:events:511:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)_

after running node app.js -i IMAGE.PNG

IMAGE.PNG is in the same directory as app.js

**Comment by kalwalt** [comment]
I can confirm this issue, i have the same result. This not happened in the past, investigating on this.

**Comment by kalwalt** [comment]
See this issue https://github.com/Carnaux/NFT-Marker-Creator/issues/94
